train: data/images/train
val: data/images/val

nc: 1
names: ['lata']

roboflow:
  workspace: albert-argumedo-ye8cj
  project: deteccion-de-latas
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/albert-argumedo-ye8cj/deteccion-de-latas/dataset/2